// resources/js/react/AsyncFormWithTable.tsx
import * as React from 'react';
import MediaLibraryCollection from '../../../vendor/spatie/laravel-medialibrary-pro/ui/medialibrary-pro-react-collection';

export default function() {
    const [value, setValue] = React.useState(window.oldValues.media);
    const [validationErrors, setValidationErrors] = React.useState(window.errors);

    function onSubmit() {
        console.log(value);

        setValidationErrors({
            [`media.${Object.keys(value)[0]}.custom_properties.tags`]: ['Field is required (this is a dummy error)'],
        });
    }

    return (
        <div>
            <h1 className="h1">Async</h1>

            <p>
                <input
                    className="border"
                    name="name"
                    type="text"
                    placeholder="name"
                    defaultValue={window.oldValues.name}
                />
            </p>

            <MediaLibraryCollection
                name="media"
                initialValue={value}
                uploadEndpoint={window.uploadEndpoint}
                translations={{
                    hint: { plural: 'Add some files!', singular: 'Add a file!' },
                    replace: 'drag or click to replace',
                }}
                validation={{ accept: ['image/png'], maxSize: 1048576 }}
                validationErrors={validationErrors}
                sortable
                onChange={setValue}
                afterItems={({
                    getCustomPropertyInputProps,
                    getCustomPropertyInputErrors,
                    getNameInputProps,
                    getNameInputErrors,
                }) => (
                    <>
                        <div className="mb-2">
                            <input className="border rounded" placeholder="image name" {...getNameInputProps()} />
                            {getNameInputErrors().map(error => (
                                <p key={error} className="text-red-500">
                                    {error}
                                </p>
                            ))}
                        </div>

                        <div className="mb-2">
                            <input
                                className="border rounded"
                                placeholder="tags"
                                {...getCustomPropertyInputProps('tags')}
                            />
                            {getCustomPropertyInputErrors('tags').map(error => (
                                <p key={error} className="text-red-500">
                                    {error}
                                </p>
                            ))}
                        </div>

                        <div className="mb-2">
                            <input
                                className="border rounded"
                                placeholder="caption"
                                {...getCustomPropertyInputProps('caption')}
                            />
                            {getCustomPropertyInputErrors('caption').map(error => (
                                <p key={error} className="text-red-500">
                                    {error}
                                </p>
                            ))}
                        </div>
                    </>
                )}
            ></MediaLibraryCollection>

            <button
                className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-2"
                onClick={onSubmit}
            >
                Submit
            </button>
        </div>
    );
}

// resources/js/vue/AsyncFormWithTable.vue
<template>
    <div>
        <h1 class="h1">Async</h1>

        <p>
            <input class="border" name="name" type="text" placeholder="name" :value="oldValues.name" />
        </p>

        <media-library-collection
            :before-upload="beforeUpload"
            :validation="{ accept: ['image/png'], maxSize: 1048576 }"
            name="media"
            :initial-value="value"
            :validation-errors="validationErrors"
            :upload-endpoint="uploadEndpoint"
            :translations="{
                hint: { plural: 'Add files please!', singular: 'Add a file please!' },
                replace: 'Click or drag to replace',
            }"
            :drag-enabled="true"
            @change="onChange"
        >
            <template
                slot="afterItems"
                slot-scope="{
                    getCustomPropertyInputProps,
                    getCustomPropertyInputListeners,
                    getCustomPropertyInputErrors,
                    getNameInputProps,
                    getNameInputListeners,
                    getNameInputErrors,
                }"
            >
                <div class="mb-2">
                    <input
                        placeholder="image name"
                        class="border rounded"
                        v-bind="getNameInputProps()"
                        v-on="getNameInputListeners()"
                    />
                    <p v-for="error in getNameInputErrors()" :key="error" class="text-red-500">
                        {{ error }}
                    </p>
                </div>

                <div class="mb-2">
                    <input
                        placeholder="tags (custom property)"
                        class="border rounded"
                        v-bind="getCustomPropertyInputProps('tags')"
                        v-on="getCustomPropertyInputListeners('tags')"
                    />
                    <p v-for="error in getCustomPropertyInputErrors('tags')" :key="error" class="text-red-500">
                        {{ error }}
                    </p>
                </div>

                <div class="mb-2">
                    <input
                        placeholder="caption (custom property)"
                        class="border rounded"
                        v-bind="getCustomPropertyInputProps('caption')"
                        v-on="getCustomPropertyInputListeners('caption')"
                    />
                    <p v-for="error in getCustomPropertyInputErrors('caption')" :key="error" class="text-red-500">
                        {{ error }}
                    </p>
                </div>
            </template>
        </media-library-collection>

        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-2" @click="onSubmit">
            Submit
        </button>
    </div>
</template>

<script>
import MediaLibraryCollection from '../../../vendor/spatie/laravel-medialibrary-pro/ui/medialibrary-pro-vue-collection';

export default {
    components: { MediaLibraryCollection },

    methods: {
        beforeUpload() {
            return new Promise(resolve => {
                resolve();
            });
        },

        onChange(value) {
            this.value = value;
        },

        onSubmit() {
            console.log(this.value);
            // TODO: axios.post().catch(errors => this.validationErrors = errors)

            this.validationErrors = {
                [`media.${Object.keys(this.value)[0]}.custom_properties.tags`]: [
                    'Field is required (this is a dummy error)',
                ],
            };
        },
    },

    data() {
        return {
            value: window.oldValues.media,
            validationErrors: window.errors,
            uploadEndpoint: window.uploadEndpoint,
            csrfToken: window.csrfToken,
            oldValues: window.oldValues,
        };
    },
};
</script>
