// resources/js/react/AsyncAttachment.tsx
import * as React from 'react';
import MediaLibraryAttachment from '../../../vendor/spatie/laravel-medialibrary-pro/ui/medialibrary-pro-react-attachment/dist';
import { MediaLibrary } from 'medialibrary-pro-core/dist/types';
import H2 from './components/H2';
import Button from './components/Button';
import Field from './components/Field';
import Grid from './components/Grid';

export default function AsyncAttachment() {
    function submit() {
        // This can also be placed in the `afterUpload` prop of the component
        /* TODO:
        axios.post(…)
        .catch(errors => {
            setValidationErrors(errors);
        });
        */

    }

    const [value, setValue] = React.useState(window.oldValues.media);
    const [validationErrors, setValidationErrors] = React.useState<MediaLibrary.State['validationErrors']>();

    return (
        <div>
            <H2>React: async attachment</H2>

            <Grid>
                <Field label="file">
                    <MediaLibraryAttachment
                        name="media"
                        uploadEndpoint={window.uploadEndpoint}
                        translations={{
                            hint: { singular: 'Add a file!', plural: 'Add some files!' },
                            replace: 'drag or click to replace',
                        }}
                        validation={{ accept: ['image/png'], maxSize: 1048576 }}
                        validationErrors={validationErrors}
                        initialValue={value}
                        onChange={setValue}
                    ></MediaLibraryAttachment>
                </Field>

                <Button
                    onClick={submit}
                >
                    Submit
                </Button>
            </Grid>
        </div>
    );
}

// resources/js/vue/AsyncAttachment.vue
<template>
    <Grid>
        <Field label="name">
            <Input name="name" id="name" placeholder="Your first name" v-model="name" />
        </Field>

        <Field label="file">
            <media-library-attachment
                name="media"
                :validation="{ accept: ['image/png'], maxSize: 1048576 }"
                :initial-value="value"
                :validation-errors="validationErrors"
                :upload-endpoint="uploadEndpoint"
                :translations="{ hint: 'Add a file please!', replace: 'Click or drag to replace' }"
                @change="onChange"
            ></media-library-attachment>
        </Field>

        <Button @click="onSubmit">Submit</Button>
    </Grid>
</template>

<script>
import MediaLibraryAttachment from '../../../vendor/spatie/laravel-medialibrary-pro/ui/medialibrary-pro-vue-attachment';
import Button from './components/Button';
import Field from './components/Field';
import Input from './components/Input';
import Grid from './components/Grid';

export default {
    components: { MediaLibraryAttachment, Button, Field, Input, Grid },

    methods: {
        onChange(value) {
            this.value = value;
        },

        onSubmit() {
            console.log('submitting', this.value);
            // axios.post().catch(errors => this.validationErrors = errors)

            const firstUuid = Object.values(this.value)[0].uuid;
            this.validationErrors = { [firstUuid]: 'error' };
        },
    },

    data() {
        return {
            name: '',
            value: window.oldValues.media,
            validationErrors: window.errors,
            uploadEndpoint: window.uploadEndpoint,
            csrfToken: window.csrfToken,
        };
    },
};
</script>
