// resources/js/react/AsyncSingle.tsx
import * as React from 'react';
import MediaLibraryClass from '../../../vendor/spatie/laravel-medialibrary-pro/ui//medialibrary-pro-core';
import MediaSingleComponent from '../../../vendor/spatie/laravel-medialibrary-pro/ui/medialibrary-pro-react-single';

export default function AsyncSingle() {
    function submit() {
        // This can also be placed in the `afterUpload` prop of the component

        /* TODO:
        axios.post(…)
        .catch(errors => {
            // setValidationErrors({ [value[0].uuid]: ['kek'] });
            // format errors to looks like this: { "uuid": ["error"]}
            setValidationErrors(formattedErrors);
        });
        */
    }

    const [value, setValue] = React.useState(window.oldValues.media);
    const [validationErrors, setValidationErrors] = React.useState<MediaLibraryClass['validationErrors']>();

    return (
        <div>
            <MediaSingleComponent
                name="media"
                tempEndpoint={window.tempEndpoint}
                translations={{
                    hint: { singular: 'Add a file!', plural: 'Add some files!' },
                    replace: 'drag or click to replace',
                }}
                validation={{ accept: ['image/png'], maxSize: 1048576 }}
                validationErrors={validationErrors}
                initialValue={value}
                onChange={setValue}
            ></MediaSingleComponent>

            <button
                className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-2"
                onClick={submit}
            >
                Submit
            </button>
        </div>
    );
}

// resources/js/vue/AsyncSingle.vue
<template>
    <div>
        <media-single-component
            name="media"
            :validation="{ accept: ['image/png'], maxSize: 1048576 }"
            :initial-value="value"
            :validation-errors="validationErrors"
            :temp-endpoint="tempEndpoint"
            :translations="{ hint: 'Add a file please!', replace: 'Click or drag to replace' }"
            @change="onChange"
        ></media-single-component>

        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-2" @click="onSubmit">
            Submit
        </button>
    </div>
</template>

<script>
import MediaSingleComponent from '../../../vendor/spatie/laravel-medialibrary-pro/ui/medialibrary-pro-vue-single';

export default {
    components: { MediaSingleComponent },

    methods: {
        onChange(value) {
            this.value = value;
        },

        onSubmit() {
            // TODO: axios.post().catch(errors => this.validationErrors = formattedErrors)
            /* this.validationErrors = { [this.value[0].uuid]: 'error' }; */
        },
    },

    data() {
        return {
            value: window.oldValues.media,
            validationErrors: window.errors,
            tempEndpoint: window.tempEndpoint,
            csrfToken: window.csrfToken,
        };
    },
};
</script>
