// resources/js/vue/AsyncAttachments.vue
<template>
    <div>
        <page-title>Vue: attachments with async submit</page-title>

        <div
            v-if="Object.keys(validationErrors).length || isUploadSuccess"
            class="rounded-sm mb-8 px-4 py-2"
            :class="Object.keys(validationErrors).length ? 'bg-red-100 text-red-500' : 'bg-green-100 text-green-500'"
        >
            <template v-if="Object.keys(validationErrors).length">
                Please correct the errors in the form
            </template>
            <template v-else>
                Your form has been submitted
            </template>
        </div>

        <Grid>
            <Field label="name">
                <Input name="name" id="name" placeholder="Your first name" v-model="value.name" />

                <error-message v-if="validationErrors && validationErrors.name">{{
                    validationErrors.name[0]
                }}</error-message>
            </Field>

            <Field label="file">
                <media-library-attachment
                    ref="mediaComponent"
                    name="media"
                    :initial-value="value.media"
                    :upload-endpoint="uploadEndpoint"
                    :validation="{ accept: ['image/png', 'image/jpeg', 'application/pdf'] }"
                    :validation-errors="validationErrors"
                    multiple
                    @change="onChange"
                ></media-library-attachment>
            </Field>

            <Button type="button" @click="onSubmit" dusk="submit">Submit</Button>
        </Grid>
    </div>
</template>

<script>
import MediaLibraryAttachment from '../../../vendor/spatie/laravel-medialibrary-pro/ui/medialibrary-pro-vue-attachment';
import Button from './components/Button';
import Field from './components/Field';
import Input from './components/Input';
import Grid from './components/Grid';
import PageTitle from './components/PageTitle';
import ErrorMessage from './components/ErrorMessage';

export default {
    components: { MediaLibraryAttachment, Button, Field, Input, Grid, ErrorMessage, PageTitle },

    methods: {
        onChange(media) {
            this.value.media = media;
        },

        onSubmit() {
            this.isUploadSuccess = false;
            this.validationErrors = {};

            axios
                .post('', this.value)
                .then(res => {
                    if (res.data.success) {
                        this.isUploadSuccess = true;
                        this.value = { name: '', media: {} };

                        this.$refs.mediaComponent.mediaLibrary.changeState(state => {
                            state.media = [];
                        });
                    }
                })
                .catch(error => {
                    console.error(error);

                    if (error && error.response && error.response.data) {
                        this.validationErrors = error.response.data.errors || {};
                    }
                });
        },
    },

    data() {
        return {
            value: {
                name: '',
                media: {},
            },
            validationErrors: {},
            uploadEndpoint: window.uploadEndpoint,
            isUploadSuccess: false,
        };
    },
};
</script>

// resources/js/react/AsyncAttachments.tsx
import * as React from 'react';
import MediaLibraryAttachment from '../../../vendor/spatie/laravel-medialibrary-pro/ui/medialibrary-pro-react-attachment/dist';
import { MediaLibrary } from 'medialibrary-pro-core/dist/types';
import PageTitle from './components/PageTitle';
import Button from './components/Button';
import Field from './components/Field';
import Grid from './components/Grid';
import ErrorMessage from './components/ErrorMessage';
import Input from './components/Input';
import Axios from 'axios';
import MediaLibraryClass from 'medialibrary-pro-core/dist';

export default function AsyncAttachments() {
    const [value, setValue] = React.useState<{
        name: string;
        media: {
            [uuid: string]: MediaLibrary.MediaAttributes;
        };
    }>({
        name: '',
        media: {},
    });
    const [validationErrors, setValidationErrors] = React.useState<MediaLibrary.State['validationErrors']>({});
    const [isUploadSuccess, setIsUploadSuccess] = React.useState(false);

    const mediaLibrary = React.useRef<MediaLibraryClass | null>(null);

    function submit() {
        setIsUploadSuccess(false);
        setValidationErrors({});

        Axios.post('', value)
            .then(res => {
                if (res.data.success) {
                    setIsUploadSuccess(true);
                    setValue({ name: '', media: {} });

                    mediaLibrary.current?.changeState(state => {
                        state.media = [];
                    });
                }
            })
            .catch(error => {
                console.error(error);

                if (error && error.response && error.response.data) {
                    setValidationErrors(error.response.data.errors);
                }
            });
    }

    return (
        <div>
            {(Object.keys(validationErrors).length || isUploadSuccess) && (
                <div
                    className={`rounded-sm mb-8 px-4 py-2 ${
                        Object.keys(validationErrors).length ? 'bg-red-100 text-red-500' : 'bg-green-100 text-green-500'
                    }`}
                >
                    {Object.keys(validationErrors).length ? (
                        <>Please correct the errors in the form</>
                    ) : (
                        <>Your form has been submitted</>
                    )}
                </div>
            )}

            <PageTitle>React: attachments with async submit</PageTitle>

            <Grid>
                <Field label="Name">
                    <Input
                        name="name"
                        type="text"
                        placeholder="Your first name"
                        value={value.name}
                        onChange={name => setValue(value => ({ ...value, name }))}
                    />
                    <ErrorMessage>{validationErrors.name}</ErrorMessage>
                </Field>

                <Field label="file">
                    <MediaLibraryAttachment
                        name="media"
                        initialValue={value.media}
                        uploadEndpoint={window.uploadEndpoint}
                        validation={{ accept: ['image/png', 'image/jpeg', 'application/pdf'] }}
                        validationErrors={validationErrors}
                        multiple
                        setMediaLibrary={mediaLib => (mediaLibrary.current = mediaLib)}
                        onChange={media => setValue(value => ({ ...value, media }))}
                    ></MediaLibraryAttachment>
                </Field>

                <Button onClick={submit} dusk="submit">
                    Submit
                </Button>
            </Grid>
        </div>
    );
}
