// resources/js/vue/FormWithTable.vue
<template>
    <form method="POST">
        <h1 class="h1">Form with Table</h1>

        <input type="hidden" name="_token" :value="csrfToken" />

        <p>
            <input class="border" name="name" type="text" placeholder="name" :value="oldValues.name" />
        </p>

        <media-table-component
            :before-upload="beforeUpload"
            :validation="{ accept: ['image/png'], maxSize: 1048576 }"
            name="media"
            :initial-value="initialValue"
            :validation-errors="validationErrors"
            :upload-endpoint="uploadEndpoint"
            :translations="{
                hint: { plural: 'Add files please!', singular: 'Add a file please!' },
                replace: 'Click or drag to replace',
            }"
            :drag-enabled="true"
        >
            <template
                slot-scope="{
                    getCustomPropertyInputProps,
                    getCustomPropertyInputListeners,
                    getCustomPropertyInputErrors,
                    getNameInputProps,
                    getNameInputListeners,
                    getNameInputErrors,
                }"
            >
                <div class="mb-2">
                    <input
                        placeholder="image name"
                        class="border rounded"
                        v-bind="getNameInputProps()"
                        v-on="getNameInputListeners()"
                    />
                    <p v-for="error in getNameInputErrors()" :key="error" class="text-red-500">
                        {{ error }}
                    </p>
                </div>

                <div class="mb-2">
                    <input
                        placeholder="tags (custom property)"
                        class="border rounded"
                        v-bind="getCustomPropertyInputProps('tags')"
                        v-on="getCustomPropertyInputListeners('tags')"
                    />
                    <p v-for="error in getCustomPropertyInputErrors('tags')" :key="error" class="text-red-500">
                        {{ error }}
                    </p>
                </div>

                <div class="mb-2">
                    <input
                        placeholder="caption (custom property)"
                        class="border rounded"
                        v-bind="getCustomPropertyInputProps('caption')"
                        v-on="getCustomPropertyInputListeners('caption')"
                    />
                    <p v-for="error in getCustomPropertyInputErrors('caption')" :key="error" class="text-red-500">
                        {{ error }}
                    </p>
                </div>
            </template>
        </media-table-component>

        <p>
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-2">Submit</button>
        </p>
    </form>
</template>

<script>
import MediaTableComponent from '../../../vendor/spatie/laravel-medialibrary-pro/ui/medialibrary-pro-vue-table';

export default {
    components: { MediaTableComponent },

    methods: {
        beforeUpload() {
            return new Promise(resolve => {
                resolve();
            });
        },
    },

    data() {
        return {
            initialValue: window.oldValues.media,
            validationErrors: window.errors,
            uploadEndpoint: window.uploadEndpoint,
            csrfToken: window.csrfToken,
            oldValues: window.oldValues,
        };
    },
};
</script>

// resources/js/react/FormWithTable.tsx
import * as React from 'react';
import MediaTableComponent from '../../../vendor/spatie/laravel-medialibrary-pro/ui/medialibrary-pro-react-table';

export default function() {
    return (
        <form method="POST">
            <h1 className="h1">Form with Table</h1>

            <input type="hidden" name="_token" defaultValue={window.csrfToken}></input>

            <p>
                <input
                    className="border"
                    name="name"
                    type="text"
                    placeholder="name"
                    defaultValue={window.oldValues.name}
                />
            </p>

            <MediaTableComponent
                name="media"
                initialValue={window.oldValues.media}
                uploadEndpoint={window.uploadEndpoint}
                translations={{
                    hint: { plural: 'Add some files!', singular: 'Add a file!' },
                    replace: 'drag or click to replace',
                }}
                validation={{ accept: ['image/png'], maxSize: 1048576 }}
                validationErrors={window.errors}
                dragEnabled
                beforeUpload={() => new Promise(resolve => resolve())}
            >
                {({
                    getCustomPropertyInputProps,
                    getCustomPropertyInputErrors,
                    getNameInputProps,
                    getNameInputErrors,
                }) => (
                    <>
                        <div className="mb-2">
                            <input className="border rounded" placeholder="image name" {...getNameInputProps()} />
                            {getNameInputErrors().map(error => (
                                <p key={error} className="text-red-500">
                                    {error}
                                </p>
                            ))}
                        </div>

                        <div className="mb-2">
                            <input
                                className="border rounded"
                                placeholder="tags"
                                {...getCustomPropertyInputProps('tags')}
                            />
                            {getCustomPropertyInputErrors('tags').map(error => (
                                <p key={error} className="text-red-500">
                                    {error}
                                </p>
                            ))}
                        </div>

                        <div className="mb-2">
                            <input
                                className="border rounded"
                                placeholder="caption"
                                {...getCustomPropertyInputProps('caption')}
                            />
                            {getCustomPropertyInputErrors('caption').map(error => (
                                <p key={error} className="text-red-500">
                                    {error}
                                </p>
                            ))}
                        </div>
                    </>
                )}
            </MediaTableComponent>

            <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded mt-2">
                Submit
            </button>
        </form>
    );
}
